install:
	cargo add yew --features csr
	cargo add serde --features derive
	cargo add uuid --features "serde v4"
	cargo add gloo
	cargo add gloo-timers
	cargo add console
	cargo add yewdux 
	cargo add serde_json
	cargo add yewdux
	cargo add wasm-bindgen
	cargo add web-sys --features "HtmlInputElement Window HtmlImageElement HtmlButtonElement"

start-app:
	trunk serve --port 7878