version="0.3.2"

[scripts]

# hot releading !!!
axum = "cargo watch -q -c -w src/ -x run"
test = "cargo watch -q -c -w tests/ -x 'test -q client -- --nocapture'"
css = "npx tailwindcss -i ./input.css -o ./public/output.css --watch"